name: OpenWrt Minimal CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache libncurses5-dev             libssl-dev python3 unzip gawk subversion git zlib1g-dev wget

      - name: Init feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Clean previous builds
        run: |
          make clean
          make dirclean

      - name: Load config
        run: |
          [ -f .config ] && echo "Using custom .config" || make defconfig

      - name: Build firmware
        run: |
          make defconfig
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-minimal-firmware
          path: bin/targets
